apiVersion: v2
type: application
version: '1.5.1'
appVersion: '1.5.1'
name: shulker-operator
description: A Kubernetes operator for managing complex and dynamic Minecraft infrastructures.
home: https://shulker.jeremylvln.fr
sources:
  - https://github.com/bridgesplash/Shulker
dependencies:
  - name: shulker-addon-matchmaking
    version: 0.0.0-internal
    condition: shulker-addon-matchmaking.enabled
    repository: file://./charts/shulker-addon-matchmaking
