name: Build and Release plugins

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project sources
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle and output version
        run: |
          ./gradlew :packages:shulker-server-agent:shadowJar :packages:shulker-proxy-agent:shadowJar
          echo $(./gradlew properties -q | grep "version:" | awk '{print $2}') > version.txt

      - name: Set version as env variable
        run: echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false

      - name: Upload shulker-server-agent Release Asset
        id: upload-release-asset-server-agent
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/java/packages/shulker-server-agent/libs/shulker-server-agent-${{ env.VERSION }}.jar
          asset_name: shulker-server-agent-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive

      - name: Upload shulker-proxy-agent Release Asset
        id: upload-release-asset-proxy-agent
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/java/packages/shulker-proxy-agent/libs/shulker-proxy-agent-${{ env.VERSION }}.jar
          asset_name: shulker-proxy-agent-${{ env.VERSION }}.jar
          asset_content_type: application/java-archive
